### ISSUE TITLE
Load balancer should not restart if nginx -t does not pass

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#2749] opened 2022-02-10 17:06 UTC
we should run `nginx -t` before the reload step. If it has a nonzero status, the reload shouldn't run and neither should the hard restart.

The way it is now we crash all sites when there's a bad config file.

**Comment by hackartisan** [comment] 2022-02-10 17:18
There is such a task but we need to mark it as always run so that it runs under the `update_conf` tag.

**Comment by acozine** [comment] 2022-12-29 15:31
Related to, possibly duplicate of, #3319.

**Closed** 2023-08-22 16:59 UTC
