### ISSUE TITLE
[LIBWWW] Upgrade Node and Gulp versions

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2457] opened 2021-09-01 15:35 UTC
library-prod3 had updated version of node and gulp stopped working.  It made use realize all the servers have a very old version of node.

We should try to upgrade.

**Comment by acozine** [comment] 2022-12-29 17:27
Closing as duplicate of #3288. Closed by #3290.

**Closed by acozine** 2022-12-29 17:27 UTC
