### ISSUE TITLE
archivesspace upgrade consistently breaks 

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#1432] opened 2020-04-10 20:54 UTC
https://aspace-staff.princeton.edu/resources/628#tree::resource_628

resources seem to miss labels on update

**Comment by faithc** [comment] 2020-04-10 20:58
Please note that the example record above is in the mss repo.

**Comment by faithc** [comment] 2020-04-14 21:10
Little more of a pressing issue that staff just discovered. It seems that the "Download EAC-CPF" option for agent records isn't exporting all of the metadata, specifically data found in the Notes subrecord. Please see the person record for Margaret Snyder in the Public Policy Papers repo: https://aspace-staff.princeton.edu/agents/agent_person/232 as an example. The exported xml record is missing the Biography/Historical note. Not sure what's going on here-whether it's something with our instance or a bug in the system. 

Also, I'm not sure why two blank Assessment records are displaying as part of this record. Assessment records, which we haven't started using yet, are normally only associated with accession and resource records. Not sure whether this is another bug.

Thanks for your help.

**Comment by jrgriffiniii** [comment] 2020-04-14 21:12
I am sorry, I will address this now @faithc

**Comment by faithc** [comment] 2020-04-14 21:22
No worries; and it's not urgent! Just not as insignificant as the other issue I noticed. :)

**Comment by jrgriffiniii** [comment] 2020-04-15 16:42
I've been looking the ArchivesSpace code base, and the export process should be located here: https://github.com/archivesspace/archivesspace/blob/master/backend/app/exporters/serializers/eac.rb#L109. I did not find there to be any step in the process for generating the XML which requires a configuration file, hence I suspect that this might be some database migration problem (the process currently maps record fields to XML elements).

**Comment by faithc** [comment] 2020-04-15 16:50
Thanks, James. And sorry, so do you mean this seems to be an issue with the code base? Something we should ping the ASpace listserv about?

**Comment by faithc** [comment] 2020-04-15 20:39
Also, just noticed another missing translation (I think this came up before too after an upgrade?): same record that I pointed to above. You'll see it if you try to edit the record by adding another Note. Thanks.

**Comment by jrgriffiniii** [comment] 2020-04-21 13:27
> The only option in the drop-down menu should be Biography/History (so, not sure why they even added a drop-down feature there...)

I've fixed this, but I'm a bit concerned given the disparity I am seeing between the entries in https://github.com/pulibrary/aspace_locales/blob/master/en.yml#L1499 and what I'm finding on the server (the file doesn't seem to have been updated).

**Comment by faithc** [comment] 2020-04-21 14:12
Ah, so it seems like all of those note options should be available for agent records, if I'm reading the yml file correctly? Any idea why they aren't showing up on the server? The reason I thought Biography/History should be the only note available is because I referenced the user manual: (https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/pages/894533774/Agent+Record+Fields), specially the section about the Notes sub-record that reads: "Note Type (dropdown list): Note types are used to guide the export of note contents to certain elements in specific data formats. The only available value is Biographical / Historical for all agent types." Perhaps this documentation is out of date?

Also, not sure if you saw my comment above about whether the inability to export this note when selecting the "Download EAC-CPF" option seems to be an issue with the code base, or is it perhaps something wonky going on with our instance?

Thanks!

**Comment by jrgriffiniii** [comment] 2020-04-23 16:18
> I suspect that this might be some database migration problem (the process currently maps record fields to XML elements).

I have spent further time attempting to diagnose this, but I'm afraid that I could not find the root cause. I did confirm that this exists in the database as expected:

```
MySQL [aspace_prod_db]> select id,agent_person_id from note where notes like '%Dr. Margaret Snyder was actively%';
+-------+-----------------+
| id    | agent_person_id |
+-------+-----------------+
| 13196 |            NULL |
| 13198 |            NULL |
| 31017 |             232 |
+-------+-----------------+
3 rows in set (0.043 sec)
```

The Agent Person record which is linked to here is the appropriate one (232). However, this still does not permit the value to be exported.

I have e-mailed the mailing list in order to try and resolve the bug. I am very sorry for the delay.

**Comment by faithc** [comment] 2020-04-23 16:54
Thanks, @jrgriffiniii!

**Comment by jrgriffiniii** [comment] 2020-04-24 13:22
Following guidance provided for me on the community mailing list, I have attempted to publish the individual note, the subnote within this, and the Agent Person record itself. None seem to have provided me with the ability to export the the biographical note into the EAC-CPF Document.

**Comment by faithc** [comment] 2020-04-24 13:36
That's so odd. Guess it's something ASpace folks will have to look into. This isn't an urgent need, so I'm not worried if this takes a bit of time for them to work on. And I know they're currently working on enhancing the agents module generally, so perhaps we should wait to see what the functionality is like once the enhancements have been implemented? Do you think it's worth submitting a JIRA ticket? Thanks for your work on this, @jrgriffiniii!

**Comment by acozine** [comment] 2022-01-11 18:04
Closing as obsolete, since we are using a hosted solution now.

**Closed by acozine** 2022-01-11 18:04 UTC
