### ISSUE TITLE
[bibdata] Add to staging environment to checkmk

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#5222] opened 2024-08-06 14:48 UTC
### What maintenance needs to be done?
- Add a script to check the rails healthcheck for bibdata
- Configure checkmk to use and alert on that script

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
So that we can quickly understand the health of our VMs from our CheckMK monitoring platform

### Acceptance criteria
 - [ ] When allsearch-api is healthy, the status displays as OK in https://pulcheck-staging.princeton.edu
 - [ ] When allsearch-api is not healthy, the status displays as Critical in https://pulcheck-staging.princeton.edu

### Implementation notes, if any
See [implementation for allsearch](https://github.com/pulibrary/princeton_ansible/pull/5191)

**Comment by christinach** [comment] 2024-08-20 15:51
closing as duplicate of https://github.com/pulibrary/princeton_ansible/issues/5197

**Closed by christinach** 2024-08-20 15:51 UTC
Labels: maintenance
