### ISSUE TITLE
Princeton data proxied 

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#711] opened 2019-08-22 14:37 UTC
pulmap is not honoring restrictions

**Comment by kayiwa** [comment] 2019-08-24 12:33
include a custom log format
```
log_format custom '$remote_addr ($http_x_real_ip) - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
```

**Comment by acozine** [comment] 2022-01-04 17:39
Closing because we have no idea what was intended and pulmap is under active development. If we still need changes, let's open a new ticket with more details.

**Closed by acozine** 2022-01-04 17:39 UTC
