### ISSUE TITLE
[Orangelight] or any rails app should be restarted when app variables change

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2456] opened 2021-09-01 10:53 UTC
When the app variables change passenger needs to be restarted (or `touch tmp/restart.txt`) for the change to take.

**Comment by hackartisan** [comment] 2021-09-03 16:55
duplicate of #2399 ?

**Comment by acozine** [comment] 2022-01-25 18:05
Closing as duplicate.

**Closed by acozine** 2022-01-25 18:05 UTC
